"""
Digest Agent
Aggregates outputs from all agents into a Markdown digest,
sends it to Discord, and persists the run to Firestore.
"""

from __future__ import annotations
import os
import httpx
from datetime import datetime

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate

from core.state import DevPulseState
from core.firestore_client import save_run


# ── LLM: Generate the digest narrative ────────────────────────────────────────

llm = ChatGroq(model="openai/gpt-oss-20b", temperature=0.3, max_retries=6)

digest_prompt = ChatPromptTemplate.from_messages([
    ("system", (
        "You are a sharp engineering newsletter editor. "
        "Write a short (2-3 sentence) opening paragraph for today's DevPulse digest. "
        "Mention the date, highlight 1 standout item from research or releases, "
        "and set an energetic tone. No filler."
    )),
    ("human", (
        "Date: {date}\n"
        "Research highlights: {research_titles}\n"
        "New releases: {release_titles}"
    )),
])

digest_chain = digest_prompt | llm


# ── Markdown builder ──────────────────────────────────────────────────────────

def build_digest(state: DevPulseState) -> str:
    date = state.get("run_date", datetime.now().strftime("%Y-%m-%d"))
    research = state.get("research_items", [])
    reviews = state.get("pr_reviews", [])
    alerts = state.get("monitor_alerts", [])
    errors = state.get("errors", [])

    # Opening blurb
    try:
        research_titles = ", ".join(r["title"] for r in research[:3]) or "none"
        release_titles = ", ".join(
            a["detail"] for a in alerts if a["source"] == "github_releases"
        )[:200] or "none"
        blurb = digest_chain.invoke({
            "date": date,
            "research_titles": research_titles,
            "release_titles": release_titles,
        }).content.strip()
    except Exception:
        blurb = f"Your DevPulse digest for {date}."

    lines = [
        f"# 🧠 DevPulse — {date}",
        "",
        blurb,
        "",
    ]

    # ── Research ──────────────────────────────────────────────────────────────
    if research:
        lines += ["---", "## 🔍 Research & Reading", ""]
        for item in research:
            source_badge = {"arxiv": "📄 ArXiv", "hackernews": "🔶 HN"}.get(item["source"], item["source"])
            lines += [
                f"### [{item['title']}]({item['url']})",
                f"*{source_badge}*",
                "",
                item["summary"],
                "",
            ]

    # ── PR Reviews ────────────────────────────────────────────────────────────
    if reviews:
        lines += ["---", "## 🔧 PR Reviews", ""]
        for pr in reviews:
            lines += [
                f"### [{pr['repo']} #{pr['pr_number']}: {pr['pr_title']}]({pr['pr_url']})",
                "",
                pr["review_summary"],
                "",
            ]
            if pr["action_items"]:
                lines.append("**Action items:**")
                for item in pr["action_items"]:
                    lines.append(f"- {item}")
                lines.append("")

    # ── Monitor Alerts ────────────────────────────────────────────────────────
    if alerts:
        lines += ["---", "## 📊 Monitoring & Releases", ""]
        for alert in alerts:
            link = f"[{alert['title']}]({alert['url']})" if alert["url"] else alert["title"]
            lines += [f"- {link} — {alert['detail']}", ""]

    # ── Errors (if any) ───────────────────────────────────────────────────────
    if errors:
        lines += ["---", "## ⚠️ Errors", ""]
        for err in errors:
            lines.append(f"- `{err}`")

    lines += ["", "---", "*Generated by DevPulse · [GitHub](https://github.com)*"]
    return "\n".join(lines)


# ── Senders ───────────────────────────────────────────────────────────────────

def send_discord(markdown: str) -> None:
    webhook = os.getenv("DISCORD_WEBHOOK_URL")
    if not webhook:
        return
    # Discord supports markdown natively — just chunk it under 2000 chars per message
    chunks = [markdown[i:i+1900] for i in range(0, len(markdown), 1900)]
    for chunk in chunks:
        httpx.post(webhook, json={"content": chunk}, timeout=10)


# ── Agent node ────────────────────────────────────────────────────────────────

def digest_agent(state: DevPulseState) -> dict:
    """
    LangGraph node: builds and sends the digest.
    """
    digest_md = build_digest(state)
    errors: list[str] = []

    try:
        send_discord(digest_md)
    except Exception as e:
        errors.append(f"digest_agent/discord: {e}")

    try:
        save_run(state, digest_md)
    except Exception as e:
        errors.append(f"digest_agent/firestore: {e}")

    return {
        "digest_markdown": digest_md,
        "digest_sent": True,
        "tasks_completed": ["digest"],
        "errors": errors,
    }